version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.0
jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - run:
          name: install mysql
          command: |
            sudo apt update
            sudo apt install mysql-server
      - aws-cli/setup:
          aws-region: AWS_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          skip-install-check: true
      - run:
          name: Download ssm plugin (Ubuntu)
          command: curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
      - run:
          name: Install ssm plugin
          command: sudo dpkg -i session-manager-plugin.deb
      - add_ssh_keys:
          fingerprints:
            - "1a:0b:24:e3:0f:ee:50:3e:9f:9b:28:95:81:cd:59:74"
      - run:
          name: test tunnel
          command: |
            ssh \
            -o "UserKnownHostsFile=/dev/null" \
            -o "StrictHostKeyChecking=no" \
            -4 -vvv -q \
            -L 9191:km-development-database.cluster-csnj5u8hrwsl.us-east-2.rds.amazonaws.com:3306 \
            -o ProxyCommand="aws ssm start-session --target %h --document AWS-StartSSHSession --parameters portNumber=%p --region=us-east-2" \
            ec2-user@i-06c66f923f50e6741
          background: true
      - run:
          name: Wait for tunnel establishment
          shell: /bin/bash
          command: |
            COUNT=0
            until nc -z 127.0.0.1 9191; do
              if [ $COUNT -ge 10 ]; then
                echo "ssh tunnel set up timeout";
                exit 1;
              fi;
              ((COUNT++))
              sleep 1
            done
      - run:
          name: test mysql
          command: |
            mysql --user=$MYSQL_USER --host=127.0.0.1 --port=9191 -p$MYSQL_PASSWORD -e "SHOW DATABASES"
workflows:
  test:
    jobs:
      - aws-cli-example
