version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.0
jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws-region: AWS_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          skip-install-check: true
      - run:
          name: Download ssm plugin (Ubuntu)
          command: curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
      - run:
          name: Install ssm plugin
          command: sudo dpkg -i session-manager-plugin.deb
     # - run:
     #     name: SSM Port Forward
     #     command: |
     #       aws ssm start-session \
     #       --target "i-06c66f923f50e6741" \
     #       --document-name AWS-StartPortForwardingSession \
     #       --parameters '{"portNumber":["'22'"],"localPortNumber":["'8080'"]}'
     #     background: true
      -run:
          name: SSH Tunnel
          command:  |
            ssh \
            -Nf -M \
            -L 9090:km-development-database.cluster-csnj5u8hrwsl.us-east-2.rds.amazonaws.com:3306 \
            -o "UserKnownHostsFile=/dev/null" \
            -o "StrictHostKeyChecking=no" \
            -o ProxyCommand="aws ssm start-session --target %h --document AWS-StartSSHSession --parameters portNumber=%p --region=us-east-2 \” \
            -vvv ec2-user@i-06c66f923f50e6741
      - run:
          name: Wait until port forwarding becomes available or timeout
          shell: /bin/bash
          command: |
            COUNT=0
            until nc -z localhost 9090; do
              if [ $COUNT -ge 15 ]; then
                echo "Port forwarding setup timeout";
                exit 1;
              fi;
              ((COUNT++))
              sleep 1
            done
      - run:
          name: Release all ssm sessions
          command: ps u | grep -- 'aws ssm start-session' | grep -v 'grep' | awk '{print $2}' | xargs kill
workflows:
  test:
    jobs:
      - aws-cli-example
