version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.0
jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - run:
          name: install mysql
          command: |
            sudo apt update
            sudo apt install mysql-server
      - aws-cli/setup:
          aws-region: AWS_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          skip-install-check: true
      - run:
          name: Download ssm plugin (Ubuntu)
          command: curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
      - run:
          name: Install ssm plugin
          command: sudo dpkg -i session-manager-plugin.deb
      - add_ssh_keys:
          fingerprints:
            - "1a:0b:24:e3:0f:ee:50:3e:9f:9b:28:95:81:cd:59:74"
      - run:
          name: test tunnel
          command: |
            ssh \
            -o "UserKnownHostsFile=/dev/null" \
            -o "StrictHostKeyChecking=no" \
            -4 -vvv \
            -L 9191:km-development-database.cluster-csnj5u8hrwsl.us-east-2.rds.amazonaws.com:3306 \
            -Nf ec2-user@18.217.248.4
      - run:
          name: test mysql
          command: |
            mysql --user=$MYSQL_USER --host=127.0.0.1 --port=9090 -p$MYSQL_PASSWORD -e "SHOW DATABASES"
      - run:
          name: Release all ssh tunnel
          command: ps u | grep -- 'ssh -L' | grep -v 'grep' | awk '{print $2}' | xargs kill
workflows:
  test:
    jobs:
      - aws-cli-example
